name: build

on:
  push:
    tags:
      - v*
      - ci*

jobs:
  build:
    runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ ubuntu-latest, windows-2019, macos-10.15 ]
          include:
            - os: ubuntu-latest
              env:
                PLATFORM: linux
                INSTALLER_NAME: Debian
                INSTALLER_EXT: deb

            - os: windows-2019
              env:
                PLATFORM: win
                INSTALLER_NAME: Windows
                INSTALLER_EXT: exe

            - os: macos-10.15
              env:
                PLATFORM: mac
                INSTALLER_NAME: Mac
                INSTALLER_EXT: pkg

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Get tag
          id: tag
          uses: dawidd6/action-get-tag@v1

      - name: Build with Gradle
        run: ./gradlew jpackage -Prelease=${{ steps.tag.outputs.tag }}

      - name: Publish native package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.env.INSTALLER_NAME }} Installer - ${{ steps.tag.outputs.tag }}
          path: build/Chipmunk-CLI-${{ steps.tag.outputs.tag }}.${{ matrix.env.INSTALLER_EXT }}


