name: build_release

on:
  push:
    tags:
      - v*
      - ci*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Build with Gradle
        run: ./gradlew :Lang:build -Prelease=${{ steps.tag.outputs.tag }}

      - name: Publish to GitHub Packages
        run: ./gradlew :Lang:publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
